
tap 'caskroom/cask'
cask 'alfred'
cask 'atom'
cask 'dropbox'
cask 'emacs'
cask 'google-chrome'
cask 'hammerspoon'
cask 'hazel'
cask 'iterm2'
cask 'keepingyouawake'
cask 'nvalt'
cask 'screenhero'
cask 'skype'
cask 'slack'
cask 'sourcetree'

tap 'caskroom/fonts'
cask 'font-dejavu-sans'
cask 'font-droid-sans-mono'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-source-code-pro'
cask 'font-terminus'
cask 'font-menlo-for-powerline'

brew 'ack'
brew 'ansible'
brew 'ctags'
brew 'direnv'
brew 'emacs'
brew 'fzf'
brew 'git'
brew 'htop-osx'
brew 'httpie'
brew 'hub'
brew 'imagemagick'
brew 'macvim'
brew 'mas'
brew 'memcached'
brew 'myrepos'
brew 'node'
brew 'postgresql'
brew 'python'
brew 'python3'
brew 'rbenv'
brew 'readline'
brew 'reattach-to-user-namespace'
brew 'redis'
brew 'ruby-build'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tmux'
brew 'tree'
brew 'vim', args: ['--with-cscope', '--with-python', '--with-lua', '--override-system-vim']
brew 'watchman'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

tap 'homebrew/versions'

tap 'neovim/neovim'
brew 'neovim/neovim/neovim', args: ['--with-cscope', '--with-python', '--with-lua', '--override-system-vim']

