
tap 'caskroom/cask'
cask 'alfred'
cask 'atom'
cask 'dropbox'
cask 'emacs'
cask 'google-chrome'
cask 'hammerspoon'
cask 'hazel'
cask 'iterm2'
cask 'keepingyouawake'
cask 'slack'
cask 'sourcetree'

tap 'caskroom/fonts'
cask 'font-dejavu-sans'
cask 'font-droid-sans-mono'
cask 'font-hack'
cask 'font-inconsolata'
cask 'font-source-code-pro'
cask 'font-terminus'

brew 'ack'
brew 'ansible'
brew 'ctags'
brew 'emacs'
brew 'fzf'
brew 'git'
brew 'htop-osx'
brew 'hub'
brew 'imagemagick'
brew 'macvim'
brew 'mas'
brew 'memcached'
brew 'python'
brew 'rbenv'
brew 'redis'
brew 'ruby-build'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tmux'
brew 'reattach-to-user-namespace'
brew 'tree'
brew 'vim', args: ['--with-override-system-vi']
brew 'wget'
brew 'zsh'

tap 'homebrew/versions'
brew 'postgresql95'

tap 'neovim/neovim'
brew 'neovim/neovim/neovim'
